name: bdaya_utils
description: Utilities used at bdaya development (includes validation...)
version: 1.0.0
repository: https://github.com/Bdaya-Dev/bdaya_dart_utils

environment:
  sdk: ">=2.12.0 <3.0.0"
# dependencies:

# dev_dependencies:
